version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/lista?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root 
      - SPRING_DATASOURCE_PASSWORD=5295452
    depends_on:
      - db

  db:
    image: mysql:5.8 # ou a versão que você preferir
    environment:
      MYSQL_DATABASE: lista
      MYSQL_USER: root
      MYSQL_PASSWORD: 5295452
      MYSQL_ROOT_PASSWORD: 5295452
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  client:
    image: listafront
    ports:
      - "80:80"

volumes:
  db-data:
