version: '3.7'
services:
  app:
    build: ./Back
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/lista?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root 
      - SPRING_DATASOURCE_PASSWORD=5295452
    depends_on:
      - db

  db:
    image: mariadb:latest # ou a versão específica que você preferir
    environment:
      MYSQL_DATABASE: lista
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 5295452
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  client:
    image: client
    ports:
      - "80:80"

volumes:
  db-data:


